//
// Generated file, do not edit! Created by opp_msgtool 6.1 from Topology/NetMsg.msg.
//

#ifndef __NETMSG_M_H
#define __NETMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetMsg;
/**
 * Class generated from <tt>Topology/NetMsg.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet NetMsg
 * {
 *     int sourceNode;
 *     double sendTime;
 * }
 * </pre>
 */
class NetMsg : public ::omnetpp::cPacket
{
  protected:
    int sourceNode = 0;
    double sendTime = 0;

  private:
    void copy(const NetMsg& other);

  protected:
    bool operator==(const NetMsg&) = delete;

  public:
    NetMsg(const char *name=nullptr, short kind=0);
    NetMsg(const NetMsg& other);
    virtual ~NetMsg();
    NetMsg& operator=(const NetMsg& other);
    virtual NetMsg *dup() const override {return new NetMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceNode() const;
    virtual void setSourceNode(int sourceNode);

    virtual double getSendTime() const;
    virtual void setSendTime(double sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NetMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __NETMSG_M_H

